"""first version

Revision ID: d054542df5b3
Revises: 
Create Date: 2023-04-04 16:23:21.712110

"""

# revision identifiers, used by Alembic.
revision = "d054542df5b3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
